apiVersion: apps/v1
kind: Deployment
metadata:
  name: university-dept
spec:
  replicas: 1
  selector:
    matchLabels:
      app: university-web
  template:
    metadata:
      labels:
        app: university-web
    spec:
      containers:
      - name: web-container
        image: university-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: university-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: university-web
